openapi: 3.0.1
info:
  title: api
  version: ''
paths:
  /borrowers/borrowers:
    post:
      description: Creates a business borrower. Business borrowers must have a unique EIN.
      operationId: BorrowersService.createBusinessBorrower
      tags:
        - Borrowers
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessBorrower'
              examples:
                Example1:
                  value:
                    address:
                      line_1: 15 Market St
                      line_2: null
                      city: San Francisco
                      state: NJ
                      zip: '94133'
                    business_contact:
                      first_name: alex
                      last_name: montana
                      phone: '4155555555'
                      email: alex@acme.co
                      title: COO
                    beneficial_owners:
                      - address:
                          line_1: 15 Market St
                          line_2: null
                          city: San Francisco
                          state: CA
                          zip: '91133'
                        date_of_birth: '1991-12-18'
                        email: jdoe@acme.com
                        first_name: Jane
                        last_name: Dough
                        percent_ownership: 2500
                        phone: '4155555555'
                        ssn: '123456789'
                        id: 63ae91f8eae458cb0d79f77e
                    id: bor_18e5a3726b3943cda2635f40e1041ba4
                    business_name: Apple Landscaping
                    business_type: corporation
                    dba_name: Apple Landscaping
                    ein: '130256721'
                    incorporation_date: '2000-12-12'
                    kyb_completion_date: '2022-11-15'
                    phone: '4152556465'
                    state_of_incorporation: DE
                    created_on: '2022-12-30T07:23:36.665Z'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BorrowerNotFound'
      summary: Create a business borrower
      security: &ref_0
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessBorrowerRequest'
            examples:
              Example1:
                value:
                  address:
                    line_1: 15 Market St
                    line_2: null
                    city: San Francisco
                    state: NJ
                    zip: '94133'
                  business_contact:
                    first_name: alex
                    last_name: montana
                    phone: '4155555555'
                    email: alex@acme.co
                    title: COO
                  beneficial_owners:
                    - address:
                        line_1: 15 Market St
                        line_2: null
                        city: San Francisco
                        state: CA
                        zip: '91133'
                      date_of_birth: '1991-12-18'
                      email: jdoe@acme.com
                      first_name: Jane
                      last_name: Dough
                      percent_ownership: 2500
                      phone: '4155555555'
                      ssn: '123456789'
                      id: 63ae91f8eae458cb0d79f77e
                  business_name: Apple Landscaping
                  business_type: corporation
                  dba_name: Apple Landscaping
                  ein: '130256721'
                  incorporation_date: '2000-12-12'
                  kyb_completion_date: '2022-11-15'
                  phone: '4152556465'
                  state_of_incorporation: DE
    get:
      description: Retrieve all borrowers associated with your account
      operationId: BorrowersService.getAllBorrowers
      tags:
        - Borrowers
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConsumerBorrower'
      summary: List all borrowers
      security: *ref_0
  /borrowers/borrowers/{borrower_id}:
    patch:
      description: >-
        Updates an existing borrower. The full borrower object needs to be
        supplied in the update request.
      operationId: BorrowersService.updateBusinessBorrower
      tags:
        - Borrowers
      parameters:
        - name: borrower_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/BusinessBorrowerId'
          examples:
            Example1:
              value: bor_18e5a3726b3943cda2635f40e1041ba4
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessBorrower'
              examples:
                Example1:
                  value:
                    address:
                      line_1: 15 Market St
                      line_2: null
                      city: San Francisco
                      state: NJ
                      zip: '94133'
                    business_contact:
                      first_name: alex
                      last_name: montana
                      phone: '4155555555'
                      email: alex@acme.co
                      title: COO
                    beneficial_owners:
                      - address:
                          line_1: 15 Market St
                          line_2: null
                          city: San Francisco
                          state: CA
                          zip: '91133'
                        date_of_birth: '1991-12-18'
                        email: jdoe@acme.com
                        first_name: Jane
                        last_name: Dough
                        percent_ownership: 2500
                        phone: '4155555555'
                        ssn: '123456789'
                        id: 63ae91f8eae458cb0d79f77e
                    id: bor_18e5a3726b3943cda2635f40e1041ba4
                    business_name: Apple Landscaping
                    business_type: corporation
                    dba_name: Apple Landscaping
                    ein: '130256721'
                    incorporation_date: '2000-12-12'
                    kyb_completion_date: '2022-11-15'
                    phone: '4152556465'
                    state_of_incorporation: DE
                    created_on: '2022-12-30T07:23:36.665Z'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BorrowerNotFound'
      summary: Update a business borrower
      security: *ref_0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessBorrowerRequest'
            examples:
              Example1:
                value:
                  address:
                    line_1: 15 Market St
                    line_2: null
                    city: San Francisco
                    state: NJ
                    zip: '94133'
                  business_contact:
                    first_name: alex
                    last_name: montana
                    phone: '4155555555'
                    email: alex@acme.co
                    title: COO
                  beneficial_owners:
                    - address:
                        line_1: 15 Market St
                        line_2: null
                        city: San Francisco
                        state: CA
                        zip: '91133'
                      date_of_birth: '1991-12-18'
                      email: jdoe@acme.com
                      first_name: Jane
                      last_name: Dough
                      percent_ownership: 2500
                      phone: '4155555555'
                      ssn: '123456789'
                      id: 63ae91f8eae458cb0d79f77e
                  business_name: Apple Landscaping
                  business_type: corporation
                  dba_name: Apple Landscaping
                  ein: '130256721'
                  incorporation_date: '2000-12-12'
                  kyb_completion_date: '2022-11-15'
                  phone: '4152556465'
                  state_of_incorporation: DE
    get:
      description: Retrieve one borrower by id
      operationId: BorrowersService.getBorrower
      tags:
        - Borrowers
      parameters:
        - name: borrower_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ConsumerBorrowerId'
          examples:
            Example1:
              value: bor_a1d0c30d77104f35b4c842b99132624e
            Example2:
              value: bor_a1d0c30d77104f35b4c842b99132624e
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsumerBorrower'
              examples:
                Example1:
                  value:
                    address:
                      line_1: 15 Main Street
                      line_2: null
                      city: Austin
                      state: TX
                      zip: '73301'
                    id: bor_a1d0c30d77104f35b4c842b99132624e
                    date_of_birth: '1991-12-18'
                    email: jdough@acme.co
                    first_name: Jane
                    last_name: Dough
                    ssn: '999888777'
                    kyc_completion_date: '2022-11-15'
                    created_on: '2022-12-31T00:58:47.828Z'
                    phone: '2065886919'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BorrowerNotFound'
              examples:
                Example1:
                  value:
                    error_type: BORROWER_ERROR
                    error_code: BORROWER_NOT_FOUND
                    error_message: The borrower resource does not exist
      summary: Retrieve a borrower by id
      security: *ref_0
  /borrowers/borrowers/consumer:
    post:
      description: Creates a consumer borrower. Consumer borrower's must have a unique SSN.
      operationId: BorrowersService.createConsumerBorrower
      tags:
        - Borrowers
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsumerBorrower'
              examples:
                Example1:
                  value:
                    address:
                      line_1: 15 Main Street
                      line_2: null
                      city: Austin
                      state: TX
                      zip: '73301'
                    id: bor_a1d0c30d77104f35b4c842b99132624e
                    date_of_birth: '1991-12-18'
                    email: jdough@acme.co
                    first_name: Jane
                    last_name: Dough
                    ssn: '999888777'
                    kyc_completion_date: '2022-11-15'
                    created_on: '2022-12-31T00:58:47.828Z'
                    phone: '2065886919'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BorrowerNotFound'
              examples:
                Example1:
                  value:
                    error_type: BORROWER_ERROR
                    error_code: DUPLICATE_SSN
                    error_message: A borrower with that SSN already exists
      summary: Create a consumer borrower
      security: *ref_0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsumerBorrowerRequest'
            examples:
              Example1:
                value:
                  address:
                    line_1: 15 Main Street
                    line_2: Unit 204
                    city: Austin
                    state: TX
                    zip: '73301'
                  date_of_birth: '1991-12-18'
                  email: jdough@acme.co
                  first_name: Jane
                  last_name: Dough
                  ssn: '999888777'
                  kyc_completion_date: '2022-11-15'
                  phone: '2065886919'
              Example2:
                value:
                  address:
                    line_1: 15 Main Street
                    line_2: Unit 204
                    city: Austin
                    state: TX
                    zip: '73301'
                  date_of_birth: '1991-12-18'
                  email: jdough@acme.co
                  first_name: Jane
                  last_name: Dough
                  ssn: '999888777'
                  kyc_completion_date: '2022-11-15'
                  phone: '2065886919'
              Example3:
                value:
                  address:
                    line_1: 15 Main Street
                    line_2: Unit 204
                    city: Austin
                    state: TX
                    zip: '73301'
                  date_of_birth: '1991-12-18'
                  email: jdough@acme.co
                  first_name: Jane
                  last_name: Dough
                  ssn: '999888777'
                  kyc_completion_date: '2022-11-15'
                  phone: '2065886919'
  /borrowers/borrowers/consumer/{borrower_id}:
    patch:
      operationId: BorrowersService.updateConsumerBorrower
      tags:
        - Borrowers
      parameters:
        - name: borrower_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ConsumerBorrowerId'
          examples:
            Example1:
              value: bor_a1d0c30d77104f35b4c842b99132624e
            Example2:
              value: bor_a1d0c30d77104f35b4c842b99132624e
            Example3:
              value: bor_a1d0c30d77104f35b4c842b99132624e
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsumerBorrower'
              examples:
                Example1:
                  value:
                    address:
                      line_1: 15 Main Street
                      line_2: null
                      city: Austin
                      state: TX
                      zip: '73301'
                    id: bor_a1d0c30d77104f35b4c842b99132624e
                    date_of_birth: '1991-12-18'
                    email: jdough@acme.co
                    first_name: Jane
                    last_name: Dough
                    ssn: '999888777'
                    kyc_completion_date: '2022-11-15'
                    created_on: '2022-12-31T00:58:47.828Z'
                    phone: '2065886919'
        '404':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BorrowerNotFound'
              examples:
                Example1:
                  value:
                    error_type: BORROWER_ERROR
                    error_code: BORROWER_NOT_FOUND
                    error_message: A borrower resource does not exist
      summary: Update a consumer borrower
      security: *ref_0
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsumerBorrowerRequest'
            examples:
              Example1:
                value:
                  address:
                    line_1: 15 Main Street
                    line_2: Unit 204
                    city: Austin
                    state: TX
                    zip: '73301'
                  date_of_birth: '1991-12-18'
                  email: jdough@acme.co
                  first_name: Jane
                  last_name: Dough
                  ssn: '999888777'
                  kyc_completion_date: '2022-11-15'
                  phone: '2065886919'
              Example2:
                value:
                  address:
                    line_1: 15 Main Street
                    line_2: Unit 204
                    city: Austin
                    state: TX
                    zip: '73301'
                  date_of_birth: '1991-12-18'
                  email: jdough@acme.co
                  first_name: Jane
                  last_name: Dough
                  ssn: '999888777'
                  kyc_completion_date: '2022-11-15'
                  phone: '2065886919'
              Example3:
                value:
                  address:
                    line_1: 15 Main Street
                    line_2: Unit 204
                    city: Austin
                    state: TX
                    zip: '73301'
                  date_of_birth: '1991-12-18'
                  email: jdough@acme.co
                  first_name: Jane
                  last_name: Dough
                  ssn: '999888777'
                  kyc_completion_date: '2022-11-15'
                  phone: '2065886919'
components:
  schemas:
    BusinessBorrowerId:
      type: string
    BeneficialOwnerId:
      type: string
    ConsumerBorrowerId:
      type: string
    BusinessBorrowerRequest:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
          description: The address of the business.
        beneficial_owners:
          type: array
          items:
            $ref: '#/components/schemas/BeneficialOwners'
          description: >
            An array of objects representing owners of the business and those
            who control the funds of the business. 

            If no one owns more than 25% of the business, just the individual
            who has ultimate control of the funds must be included. 

            A maximum of 5 objects can be added.
        business_contact:
          $ref: '#/components/schemas/BusinessContact'
          description: The person executing the loan agreement.
        business_name:
          type: string
          description: Legal name of the business.
          example: Apple Landscaping
        business_type:
          $ref: '#/components/schemas/BusinessType'
          description: The type of business entity.
        dba_name:
          type: string
          description: Doing-business-as name of the business
          example: Apple Landscaping
        ein:
          type: string
          description: >-
            9-digit IRS employee identification number of the business (e.g.
            345543221)
          example: '130256721'
        incorporation_date:
          type: string
          description: Incorporation date of the business (YYYY-MM-DD)
          example: '2000-12-12'
        kyb_completion_date:
          type: string
          description: Date kyb completed on the business (YYYY-MM-DD)
          example: '2022-11-15'
        state_of_incorporation:
          type: string
          description: Required 2-digit US state code (e.g. CA, IL, FL, …)
          example: DE
        phone:
          type: string
          description: The phone number of the business
          example: '4152556465'
      required:
        - address
        - beneficial_owners
        - business_contact
        - business_name
        - business_type
        - dba_name
        - ein
        - incorporation_date
        - kyb_completion_date
        - state_of_incorporation
        - phone
    BusinessBorrower:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/BusinessBorrowerId'
        address:
          $ref: '#/components/schemas/Address'
        beneficial_owners:
          type: array
          items:
            $ref: '#/components/schemas/BeneficialOwners'
          description: >
            An array of objects representing owners of the business and those
            who control the funds of the business. 

            If no one owns more than 25% of the business, just the individual
            who has ultimate control of the funds must be included. 

            A maximum of 5 objects can be added.
        business_contact:
          $ref: '#/components/schemas/BusinessContact'
          description: The person executing the loan agreement.
        business_name:
          type: string
          description: Legal name of the business
          example: Apple Landscaping
        business_type:
          $ref: '#/components/schemas/BusinessType'
          description: The type of business entity.
        created_on:
          type: string
          description: Time stamp of borrower's creation date
          example: '2022-12-30T07:23:36.665Z'
        dba_name:
          type: string
          description: Doing-business-as name of the business
          example: Apple Landscaping
        ein:
          type: string
          description: >-
            9-digit IRS employee identification number of the business (e.g.
            345543221)
          example: '130256721'
        incorporation_date:
          type: string
          description: Incorporation date of the business (YYYY-MM-DD)
          example: '2000-12-12'
        kyb_completion_date:
          type: string
          description: Date kyb completed on the business (YYYY-MM-DD)
          example: '2022-11-15'
        phone:
          type: string
          description: The phone number of the business
          example: '4152556465'
        state_of_incorporation:
          type: string
          description: Required 2-digit US state code (e.g. CA, IL, FL, …)
          example: DE
      required:
        - id
        - address
        - beneficial_owners
        - business_contact
        - business_name
        - business_type
        - created_on
        - dba_name
        - ein
        - incorporation_date
        - kyb_completion_date
        - phone
        - state_of_incorporation
    BeneficialOwners:
      type: object
      description: >-
        A person who owns owns 25% or more of the business as well as those who
        control the funds.
      properties:
        id:
          $ref: '#/components/schemas/BeneficialOwnerId'
        address:
          $ref: '#/components/schemas/Address'
          description: The person's address.
        date_of_birth:
          type: string
          description: The person's date of birth (YYYY-MM-DD)
        email:
          type: string
          description: The person's valid email address
        first_name:
          type: string
          description: The person's first name
        last_name:
          type: string
          description: The person's last name
        phone:
          type: string
          description: The person's 10-digit US phone number (e.g. 4152251000)
        percent_ownership:
          type: integer
          description: >-
            The percent ownership the person has in the business in basis points
            (e.g. 2500 for 25%)
        ssn:
          type: string
          description: The person's 9-digit US social security number (e.g. 123456789)
      required:
        - id
        - address
        - date_of_birth
        - email
        - first_name
        - last_name
        - phone
        - percent_ownership
        - ssn
    BusinessContact:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        email:
          type: string
        title:
          type: string
      required:
        - first_name
        - last_name
        - phone
        - email
        - title
    BusinessType:
      type: string
      enum:
        - corporation
        - llc
        - partnership
        - sole_proprietorship
    ConsumerBorrowerRequest:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
          description: The address of the borrower
        date_of_birth:
          type: string
          description: The borrower's date of birth (YYYY-MM-DD)
          example: '1991-12-18'
        email:
          type: string
          description: The borrower's valid email address
          example: jdough@acme.co
        first_name:
          type: string
          description: The borrower's first name
          example: Jane
        last_name:
          type: string
          description: The borrower's last name
          example: Dough
        kyc_completion_date:
          type: string
          description: Date kyc completed on the borrower (YYYY-MM-DD)
          example: '2022-11-15'
        phone:
          type: string
          description: The borrower's 10-digit US phone number (e.g. 4152775050)
          example: '2065886919'
        ssn:
          type: string
          description: 9-digit social security number of the borrower (e.g. 345543221)
          example: '999888777'
      required:
        - address
        - date_of_birth
        - email
        - first_name
        - last_name
        - kyc_completion_date
        - phone
        - ssn
    ConsumerBorrower:
      type: object
      properties:
        address:
          $ref: '#/components/schemas/Address'
          description: The address of the borrower
        date_of_birth:
          type: string
          description: The borrower's date of birth (YYYY-MM-DD)
          example: '1991-12-18'
        id:
          $ref: '#/components/schemas/ConsumerBorrowerId'
          description: The ID of the borrower
        email:
          type: string
          description: The borrower's valid email address
          example: jdough@acme.co
        first_name:
          type: string
          description: The borrower's first name
          example: Jane
        last_name:
          type: string
          description: The borrower's last name
          example: Dough
        kyc_completion_date:
          type: string
          description: Date kyc completed on the borrower (YYYY-MM-DD)
          example: '2022-11-15'
        phone:
          type: string
          description: The borrower's 10-digit US phone number (e.g. 4152775050)
          example: '2065886919'
        ssn:
          type: string
          description: 9-digit social security number of the borrower (e.g. 345543221)
          example: '999888777'
        created_on:
          type: string
          format: date-time
          description: The date the borrower was created
          example: '2022-12-31T00:58:47.828Z'
      required:
        - address
        - date_of_birth
        - id
        - email
        - first_name
        - last_name
        - kyc_completion_date
        - phone
        - ssn
        - created_on
    RejectionType:
      type: object
      properties:
        reason:
          type: string
        reason_message:
          type: string
      required:
        - reason
        - reason_message
    id:
      type: string
    Address:
      type: object
      properties:
        line_1:
          type: string
        line_2:
          type: string
        city:
          type: string
        state:
          type: string
          description: 2-digit US state code (e.g. CA, IL, FL)
        zip:
          type: string
          description: 5-digit US zip code
      required:
        - line_1
        - city
        - state
        - zip
    BaseErrorBody:
      type: object
      properties:
        error_type:
          type: string
        error_code:
          type: string
        error_message:
          type: string
      required:
        - error_type
        - error_code
        - error_message
    InvalidInput:
      type: object
      properties:
        error_detail:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
      required:
        - error_detail
      allOf:
        - $ref: '#/components/schemas/BaseErrorBody'
    ErrorDetail:
      type: object
      properties:
        value:
          type: string
        msg:
          type: string
        param:
          type: string
        location:
          type: string
      required:
        - value
        - msg
        - param
        - location
    DuplicateEin:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/BaseErrorBody'
    DuplicateSsn:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/BaseErrorBody'
    BorrowerNotFound:
      type: object
      properties: {}
      allOf:
        - $ref: '#/components/schemas/BaseErrorBody'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
servers:
  - url: https://production.pier-finance.com/api
    description: Production
  - url: https://sandbox.pier-finance.com/api
    description: >-
      Sandbox (The sandbox is designed to mimic the production environment, with
      a few exceptions. 

      Loan agreements created in the sandbox will have large `draft` watermarks
      and funds flows will only occur in production. 

      Sandbox API keys are prefixed with `test_` while production API keys are 
      prefixed with `prod_`.

      )
